Importing Pandas and Numpy

In [30]:
import numpy as np
import pandas as pd
import pprint

In [31]:
url = "./K.SriKausik_S2/Heart_disease_statlog.csv"
names = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
dataset = pd.read_csv(url, header=1,names=names)


In [32]:
dataset.describe

<bound method NDFrame.describe of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     67    0   2       115   564    0        2      160      0      1.6   
1     57    1   1       124   261    0        0      141      0      0.3   
2     64    1   3       128   263    0        0      105      1      0.2   
3     74    0   1       120   269    0        2      121      1      0.2   
4     65    1   3       120   177    0        0      140      0      0.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
264   52    1   2       172   199    1        0      162      0      0.5   
265   44    1   1       120   263    0        0      173      0      0.0   
266   56    0   1       140   294    0        2      153      0      1.3   
267   57    1   3       140   192    0        0      148      0      0.4   
268   67    1   3       160   286    0        2      108      1      1.5   

     slope  ca  thal  target  
0        1   0     3  

In [33]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   67    0   2       115   564    0        2      160      0      1.6      1   
1   57    1   1       124   261    0        0      141      0      0.3      0   
2   64    1   3       128   263    0        0      105      1      0.2      1   
3   74    0   1       120   269    0        2      121      1      0.2      0   
4   65    1   3       120   177    0        0      140      0      0.4      0   

   ca  thal  target  
0   0     3       0  
1   0     3       1  
2   1     3       0  
3   1     1       0  
4   0     3       0

In [34]:
x = dataset.drop('target',1) #type:ignore
y = dataset['target']

C:\Users\Kaushik\AppData\Local\Temp\ipykernel_14368\920227641.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = dataset.drop('target',1) #type:ignore


droppinng the target feature cause it is one our model need to predict

In [35]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     67    0   2       115   564    0        2      160      0      1.6   
1     57    1   1       124   261    0        0      141      0      0.3   
2     64    1   3       128   263    0        0      105      1      0.2   
3     74    0   1       120   269    0        2      121      1      0.2   
4     65    1   3       120   177    0        0      140      0      0.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
264   52    1   2       172   199    1        0      162      0      0.5   
265   44    1   1       120   263    0        0      173      0      0.0   
266   56    0   1       140   294    0        2      153      0      1.3   
267   57    1   3       140   192    0        0      148      0      0.4   
268   67    1   3       160   286    0        2      108      1      1.5   

     slope  ca  thal  
0        1   0     3  
1        0   0     3  
2        1   1     3  
3        0   1     1  
4        0   0     3  
..     ...  ..   ...  
264      0   0     3  
265      0   0     3  
266      1   0     1  
267      1   0     2  
268      1   3     1  

[269 rows x 13 columns]

In [36]:
x.shape

(269, 13)

In [37]:
y

0      0
1      1
2      0
3      0
4      0
      ..
264    0
265    0
266    0
267    0
268    1
Name: target, Length: 269, dtype: int64

In [38]:
y.shape

(269,)

In [39]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

In [40]:
X_train.shape

(242, 13)

**Data Preprocessing**

In [41]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [48]:
X_train

array([[-1.05213062,  0.65723106,  0.86665919, ...,  0.69346513,
         2.5265664 ,  1.22081463],
       [ 0.4176753 ,  0.65723106, -0.16650103, ...,  0.69346513,
        -0.70281249,  1.22081463],
       [-1.27825461, -1.52153491,  0.86665919, ...,  0.69346513,
        -0.70281249,  1.22081463],
       ...,
       [ 1.32217125, -1.52153491, -2.23282146, ...,  2.32277155,
        -0.70281249, -0.86708036],
       [ 1.32217125,  0.65723106, -1.19966124, ...,  0.69346513,
         2.5265664 ,  0.17686714],
       [ 1.54829524, -1.52153491, -0.16650103, ...,  0.69346513,
        -0.70281249, -0.86708036]])

**Applying various classifiers for obtaining the model**

**1) Random Forest Classifier**

In [44]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(random_state=0)
classifier.fit(X_train, y_train)

# Predicting the test set
y_pred = classifier.predict(X_test)


In [45]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1], dtype=int64)

In [52]:
#getting the confussion matrix and calculating the accuracy score of the model

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print("Confussion matrix :")
print(cm)
print("Accuracy = "+str(accuracy_score(y_test, y_pred)*100)[0:8] + "%")

Confussion matrix :
[[13  1]
 [ 3 10]]
Accuracy = 85.18518%


**2) Logistic Regression Classifier**

In [60]:
from sklearn.linear_model import LogisticRegression 

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = reg_log.predict(X_test)

In [58]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1], dtype=int64)

In [59]:
#getting the confussion matrix and calculating the accuracy score of the model

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print("Confussion matrix :")
print(cm)
print("Accuracy = "+str(accuracy_score(y_test, y_pred)*100)[0:8] + "%")

Confussion matrix :
[[14  0]
 [ 2 11]]
Accuracy = 92.59259%


**3) SVC classifier**

In [62]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

In [63]:
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1], dtype=int64)

In [64]:
#getting the confussion matrix and calculating the accuracy score of the model

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print("Confussion matrix :")
print(cm)
print("Accuracy = "+str(accuracy_score(y_test, y_pred)*100)[0:8] + "%")

Confussion matrix :
[[14  0]
 [ 1 12]]
Accuracy = 96.29629%


**4) KNN Classifier**

In [65]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [66]:
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1], dtype=int64)

In [67]:
#getting the confussion matrix and calculating the accuracy score of the model

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print("Confussion matrix :")
print(cm)
print("Accuracy = "+str(accuracy_score(y_test, y_pred)*100)[0:8] + "%")

Confussion matrix :
[[14  0]
 [ 1 12]]
Accuracy = 96.29629%
