In [2]:
import numpy as np
import pandas as pd
import pprint

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
names = ['sex','lenght','diameter','height','whole','shucked','viscera','shell','rings']
dataset = pd.read_csv(url,header=1, names=names)

In [4]:
dataset.head()

sex  lenght  diameter  height   whole  shucked  viscera  shell  rings
0   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
1   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
2   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7
3   I   0.425     0.300   0.095  0.3515   0.1410   0.0775  0.120      8
4   F   0.530     0.415   0.150  0.7775   0.2370   0.1415  0.330     20

In [5]:
X = dataset.drop('sex', 1)
x = dataset.drop('rings',1)
y = dataset['rings']

C:\Users\Kaushik\AppData\Local\Temp\ipykernel_11208\139365320.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dataset.drop('sex', 1)
C:\Users\Kaushik\AppData\Local\Temp\ipykernel_11208\139365320.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = dataset.drop('rings',1)


In [6]:
X

lenght  diameter  height   whole  shucked  viscera   shell  rings
0      0.530     0.420   0.135  0.6770   0.2565   0.1415  0.2100      9
1      0.440     0.365   0.125  0.5160   0.2155   0.1140  0.1550     10
2      0.330     0.255   0.080  0.2050   0.0895   0.0395  0.0550      7
3      0.425     0.300   0.095  0.3515   0.1410   0.0775  0.1200      8
4      0.530     0.415   0.150  0.7775   0.2370   0.1415  0.3300     20
...      ...       ...     ...     ...      ...      ...     ...    ...
4170   0.565     0.450   0.165  0.8870   0.3700   0.2390  0.2490     11
4171   0.590     0.440   0.135  0.9660   0.4390   0.2145  0.2605     10
4172   0.600     0.475   0.205  1.1760   0.5255   0.2875  0.3080      9
4173   0.625     0.485   0.150  1.0945   0.5310   0.2610  0.2960     10
4174   0.710     0.555   0.195  1.9485   0.9455   0.3765  0.4950     12

[4175 rows x 8 columns]

In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

In [9]:
X_train.shape

(3340, 8)

**Data Preprocessing**

In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Apply Random Forest classifier and get the model**

In [11]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=8, random_state=40)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [12]:
y_pred

array([10,  8,  9,  8,  6, 13, 10, 11, 11, 10,  9, 16, 10,  6, 13, 10, 10,
       11,  4,  9,  7, 13,  8, 12,  9, 11, 11, 12,  9, 10,  4,  8, 11,  4,
       10,  9,  7, 11, 10,  9,  8, 10,  6,  8, 10, 13, 11,  7,  6,  9, 12,
        7,  7,  8, 10, 10,  8,  9, 15, 13,  8,  7,  4, 11, 14, 11, 10, 10,
       11, 11, 11,  6,  7,  8, 16, 10, 12, 11,  9, 11,  8, 10, 11, 12,  8,
       11, 11, 10, 15,  8,  9, 10,  8,  9,  9, 11, 12,  8, 10,  8, 10,  8,
       11,  4,  9,  8,  9, 11, 12,  9,  8, 10,  9, 12,  8, 11, 12, 11, 12,
        4, 10, 13, 10,  7, 12,  5,  7,  8, 12, 10,  5, 10, 12, 12,  9, 12,
       12,  9,  7, 11,  8, 10,  8, 13, 11, 11, 10, 11,  8, 13, 10, 11, 11,
        9,  8,  9,  7,  7, 13, 12, 10,  9,  9,  7,  8,  9,  9, 11,  9, 12,
       13, 11,  9,  8,  6,  9,  7, 10,  6, 10, 12,  6,  7,  8, 13,  8, 11,
       10, 10, 13, 12,  9, 11, 10,  8, 12, 10, 12, 15,  4,  4, 10, 11,  6,
        8, 11,  5,  9, 10, 11,  7,  9, 14, 10, 14, 13, 11,  8, 11,  7, 13,
        8, 10, 14, 11,  8

In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)*100)[0:8]+"%")

[[  1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   1  45   3   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0  69   3   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0 108   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 146   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0 125   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0 100   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   2   8   7  54   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   1   6   6   4  20   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

**Apply Logistic Regression classifier and get the model**

In [14]:
from sklearn.linear_model import LogisticRegression
reg_log = LogisticRegression()
reg_log.fit(X_train, y_train)
y_pred = reg_log.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy :' + str(accuracy_score(y_test, y_pred)*100)[0:3]+"%")

[[  0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   5   8   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   1   7  10   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  2   0   2  29  16   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   1   0  54  17   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   6  94   8   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 139   7   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   4 121   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0  32  67   1   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0  64   4   3   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   3   6  28   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

C:\Users\Kaushik\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


**SVC Classifier**

In [15]:
from sklearn.svm import SVC
reg_svc = SVC()
reg_svc.fit(X_train, y_train)
y_pred = reg_svc.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy :' + str(accuracy_score(y_test, y_pred)*100)[0:10]+"%")

[[  0   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  12   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0  49   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0  72   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0 108   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 144   2   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0 123   2   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   1  95   4   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   2  69   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  37   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

**KNN  Classifier**

In [16]:
from sklearn.neighbors import KNeighborsClassifier
reg_knn = KNeighborsClassifier()
reg_knn.fit(X_train, y_train)
y_pred = reg_knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   1  46   2   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   1  67   4   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0  99   9   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   3 136   7   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  11 112   2   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0  15  81   4   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0  25  43   2   1   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   1  11  25   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

In [17]:
X_train.shape

(3340, 8)

In [18]:
X_train.shape

(3340, 8)

In [19]:
X_test.shape

(835, 8)

# PCA

**Applying Dimensionality Reduction**

In [20]:
print(dataset)

     sex  lenght  diameter  height   whole  shucked  viscera   shell  rings
0      F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.2100      9
1      M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.1550     10
2      I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.0550      7
3      I   0.425     0.300   0.095  0.3515   0.1410   0.0775  0.1200      8
4      F   0.530     0.415   0.150  0.7775   0.2370   0.1415  0.3300     20
...   ..     ...       ...     ...     ...      ...      ...     ...    ...
4170   F   0.565     0.450   0.165  0.8870   0.3700   0.2390  0.2490     11
4171   M   0.590     0.440   0.135  0.9660   0.4390   0.2145  0.2605     10
4172   M   0.600     0.475   0.205  1.1760   0.5255   0.2875  0.3080      9
4173   F   0.625     0.485   0.150  1.0945   0.5310   0.2610  0.2960     10
4174   M   0.710     0.555   0.195  1.9485   0.9455   0.3765  0.4950     12

[4175 rows x 9 columns]


In [21]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)
print (X_std[0:5])
print ("The shape of Feature Matrix is -",X_std.shape)

[[ 0.04955097  0.12168572 -0.10853637 -0.30991496 -0.46391152 -0.35715163
  -0.20757947 -0.28951041]
 [-0.69999716 -0.43261072 -0.34766004 -0.63826215 -0.64864342 -0.60806088
  -0.60272844  0.02073239]
 [-1.61611154 -1.54120359 -1.42371656 -1.27252287 -1.21635609 -1.28779685
  -1.32118111 -0.909996  ]
 [-0.82492185 -1.08768832 -1.06503106 -0.97374732 -0.9843148  -0.94108588
  -0.85418687 -0.59975321]
 [ 0.04955097  0.07129513  0.25014913 -0.10495289 -0.55177182 -0.35715163
   0.65456372  3.12316039]]
The shape of Feature Matrix is - (4175, 8)


In [22]:
X_covariance_matrix = np.cov(X_std.T)

In [23]:
X_covariance_matrix

array([[1.00023958, 0.98704303, 0.82768643, 0.92545011, 0.89808716,
        0.90319266, 0.89787498, 0.55713555],
       [0.98704303, 1.00023958, 0.83384359, 0.92564696, 0.8933376 ,
        0.89990599, 0.90551098, 0.57502909],
       [0.82768643, 0.83384359, 1.00023958, 0.81934205, 0.77506768,
        0.79841519, 0.81745908, 0.55813331],
       [0.92545011, 0.92564696, 0.81934205, 1.00023958, 0.96962483,
        0.96659179, 0.95556401, 0.54083091],
       [0.89808716, 0.8933376 , 0.77506768, 0.96962483, 1.00023958,
        0.93215609, 0.88277793, 0.42121217],
       [0.90319266, 0.89990599, 0.79841519, 0.96659179, 0.93215609,
        1.00023958, 0.90783201, 0.50426933],
       [0.89787498, 0.90551098, 0.81745908, 0.95556401, 0.88277793,
        0.90783201, 1.00023958, 0.62808959],
       [0.55713555, 0.57502909, 0.55813331, 0.54083091, 0.42121217,
        0.50426933, 0.62808959, 1.00023958]])

In [24]:
eig_vals, eig_vecs = np.linalg.eig(X_covariance_matrix)
print('Eigenvectors \n%s' %eig_vecs) 
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 3.72126203e-01 -6.83924971e-02 -3.12846086e-02  6.04058041e-01
  -6.98809902e-01  1.64071880e-02  4.73916922e-02  1.13694244e-02]
 [ 3.73083019e-01 -4.02130817e-02 -4.12670615e-02  5.87564664e-01
   7.12993844e-01 -2.82782587e-04  2.34452533e-02 -5.78513889e-02]
 [ 3.40013500e-01  7.11041729e-02 -8.99603502e-01 -2.57087052e-01
  -8.67269626e-03  2.70579526e-03 -2.65454190e-02  5.62815034e-02]
 [ 3.78298259e-01 -1.37494097e-01  2.06167746e-01 -2.41805298e-01
   8.41109222e-03  8.50259079e-01 -1.17266898e-01 -1.57507264e-02]
 [ 3.62436225e-01 -2.99161614e-01  2.07830522e-01 -1.83400129e-01
   9.33502825e-03 -3.91132666e-01 -6.25209423e-01  3.97937747e-01]
 [ 3.68545065e-01 -1.73096741e-01  1.97355741e-01 -2.65203043e-01
   2.72948356e-02 -2.04169444e-01  7.65593700e-01  3.10429102e-01]
 [ 3.70748110e-01  4.54659970e-02  1.62007770e-01 -2.43907586e-01
  -4.75079906e-02 -2.85597228e-01 -3.21300618e-02 -8.30593840e-01]
 [ 2.42843063e-01  9.20987315e-01  1.92710589e-01 -4.31

In [25]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort(key=lambda x: x[0], reverse=True)
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
6.714210208478442
0.6955185463404436
0.258506975748018
0.1660931063986687
0.08497532726759324
0.0635074385517231
0.012702426245892677
0.006402597706165589


In [26]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)
print ("Variance captured by each component is \n",var_exp)
print(40 * '-')
print ("Cumulative variance captured as we travel each component \n",cum_var_exp)

Variance captured by each component is 
 [83.90752518020659, 8.691899438398233, 3.2305632238689417, 2.0756665452336605, 1.061937173697407, 0.7936528398649463, 0.1587422968573533, 0.08001330187285972]
----------------------------------------
Cumulative variance captured as we travel each component 
 [ 83.90752518  92.59942462  95.82998784  97.90565439  98.96759156
  99.7612444   99.9199867  100.        ]


In [27]:
print ("All Eigen Values along with Eigen Vectors")
pprint.pprint(eig_pairs)
print(40 * '-')
matrix_w = np.hstack((eig_pairs[0][1].reshape(8,1),eig_pairs[1][1].reshape(8,1)))
print ('Matrix W:\n', matrix_w)

All Eigen Values along with Eigen Vectors
[(6.714210208478442,
  array([0.3721262 , 0.37308302, 0.3400135 , 0.37829826, 0.36243623,
       0.36854507, 0.37074811, 0.24284306])),
 (0.6955185463404436,
  array([-0.0683925 , -0.04021308,  0.07110417, -0.1374941 , -0.29916161,
       -0.17309674,  0.045466  ,  0.92098732])),
 (0.258506975748018,
  array([-0.03128461, -0.04126706, -0.8996035 ,  0.20616775,  0.20783052,
        0.19735574,  0.16200777,  0.19271059])),
 (0.1660931063986687,
  array([ 0.60405804,  0.58756466, -0.25708705, -0.2418053 , -0.18340013,
       -0.26520304, -0.24390759, -0.04311522])),
 (0.08497532726759324,
  array([ 0.01136942, -0.05785139,  0.0562815 , -0.01575073,  0.39793775,
        0.3104291 , -0.83059384,  0.22023046])),
 (0.0635074385517231,
  array([ 0.04739169,  0.02344525, -0.02654542, -0.1172669 , -0.62520942,
        0.7655937 , -0.03213006, -0.06852215])),
 (0.012702426245892677,
  array([-0.6988099 ,  0.71299384, -0.0086727 ,  0.00841109,  0.00933503,

In [28]:
Y = X_std.dot(matrix_w) 
print (Y[0:5])

[[-0.53733614 -0.0488551 ]
 [-1.45916499  0.41930155]
 [-3.76814468 -0.06512446]
 [-2.60918291  0.02448067]
 [ 0.75989634  3.15900336]]


In [29]:
Y
print(Y.shape)

(4175, 2)


In [30]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Y, y, test_size=0.2, random_state=21)

In [31]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Apply Random forest on the Dimension reduced data**

In [32]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [33]:
y_pred

array([10,  9,  9,  7,  7, 13,  9,  9, 10, 13, 10, 13,  9,  7, 13,  9, 13,
        9,  7, 10,  7, 13,  9, 13,  9, 10, 10, 10,  8,  9,  7, 10, 15,  7,
        9,  9,  8, 13, 13,  9,  9,  9,  7,  8, 10, 15, 10,  7,  7,  9, 10,
        9,  7,  7, 13, 10,  9,  8, 15, 10,  7,  7,  7,  9, 11, 10, 10, 10,
       10, 10, 15,  7,  7,  7, 13, 13, 10, 10,  9,  9,  8,  9, 10, 13,  8,
       13, 10, 10, 13,  8,  9, 10,  8,  8,  8, 10, 10,  7, 10,  8,  9,  8,
       13,  7,  8, 10,  8, 10, 13,  9,  9, 10, 10, 10,  9, 13, 10, 10, 10,
        7, 10, 10, 10,  7, 10,  7,  8,  9, 10,  9,  7, 10, 13, 10, 10, 10,
       13,  8,  7,  9,  9,  9,  9, 15, 10,  9,  9, 13,  9, 15,  9, 10, 10,
        8,  8,  8,  9,  7, 13, 10, 10,  8, 10,  7,  8,  8, 10, 13,  9, 13,
       15, 10,  8, 10,  7,  9,  8, 13,  7, 10, 13,  7,  7,  9, 13,  9, 13,
        9, 10, 13,  9, 10, 15,  9,  8, 10,  9, 10, 15,  7,  7,  9,  9,  7,
        8, 10,  7, 10,  9, 10,  7,  9, 13, 10, 13, 15,  9,  7, 10,  7, 10,
        9,  9, 13, 10,  8

**Performance Evaluation on new Data**

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy :' + str(accuracy_score(y_test, y_pred)*100)[0:4]+"%")

[[ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 45  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 55 10  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19 40 40  9  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39 64 43  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2 64 59  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 31 57  0  0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5 48  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 13  1  0 23  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  2  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  1  0  0 13  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0 14  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  6  0  7  0  0  0  0  0  0  0  0]
 [ 0  0  0

**Logistic Regression Classifier**

In [35]:
from sklearn.linear_model import LogisticRegression
reg_log = LogisticRegression()
reg_log.fit(X_train, y_train)
y_pred = reg_log.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy :' + str(accuracy_score(y_test, y_pred)*100)[0:9]+"%")

[[  0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  13   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   3  15   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0  27  22   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0  56  16   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   2  95  11   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   4 136   6   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  11 114   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0  39  61   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   1  68   0   2   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   7   5  25   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

C:\Users\Kaushik\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


**SVC Classifier**

In [36]:
from sklearn.svm import SVC
reg_svc = SVC()
reg_svc.fit(X_train, y_train)
y_pred = reg_svc.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0  49   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0  69   3   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   1 102   5   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 135  11   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   2 118   5   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   5  91   4   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0  15  55   1   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   0   2  35   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0

**KNN Classfier**

In [37]:
from sklearn.neighbors import KNeighborsClassifier
reg_knn = KNeighborsClassifier()
reg_knn.fit(X_train, y_train)
y_pred = reg_knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0  48   1   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   1  70   1   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   1 101   6   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   3 135   8   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   3 114   8   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   1   7  88   4   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0  12  58   1   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   0   2  35   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0